### PR TITLE
fix: add custom pagination

### LINKED ISSUE #304: Alphabetical `Previous` and `Next` links at the bottom of each page
**Describe the bug**
`Previous` and `Next` links at the bottom of each page are linking to the alphabetical next/previous page, 

**To Reproduce**
1. Go to any page. For example `/intro`.
2. Scroll down to see the `Previous` and `Next` links.
3. See links to the alphabetically _previous_ and _next_ pages.
image

**Expected behavior**
They should link to the `Previous` or `Next` page, based on docs structure, not alphabetically.

### PR DESCRIPTION
**Pull request by a2937**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #304

I created a new component to take care of the issue with the previous and next issues. I basically reassign the next and previous values to what it is supposed to be present. There is a slight concern that the next link leads to the "Github" link on the side bar, but I'm not sure of the correct way to fix it. Additionally I like having code that is designed to keep indexes in bounds.

### CODE REVIEW

**Comment by a2937** [comment]
I think I forgot to do something.

**Review by raisedadead — COMMENTED** [review]
I piggy-backed this PR and dropped the pagination on two pages.

**Review by raisedadead — CHANGES_REQUESTED** [review]
Lets use `kebab-case` with files names - at least for the TS ones. I will do a more all round cleanup later.

**Comment by gikf** [comment]
> There is a slight concern that the next link leads to the "Github" link on the side bar, but I'm not sure of the correct way to fix it.

Would it be possible to use `updatePagination` to disable the `next` link? If yes, then come to mind two options:
- Checking if next link would correspond to page from `docs` collection.
- Adding optional `external` property to the link item, which would be used to ignore external links from the `next/prev`.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
